language: php

php:
  - 5.3
  - 5.4
  
sudo: false  
  
before_install:
  - composer selfupdate

install: 
  - composer update
    
script:
  - phpunit

notifications:
  email:
    - leonardo.proietti@gmail.com

